name: Unit Test
on: push

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: ubuntu-latest
    container:
      image: dockware.6.5.rc
      env:
        PHP_VERSION: 8.1

    steps:
      - name: Install dependencies
        run:
          apt install php8.1-gmp
          composer require hardcastle/xrpl_php dev-master
          composer require --dev phpunit/phpunit ^9
      - name: Run PHPUnit
        run: make phpunit

