name: Unit Test
on: push

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: ubuntu-latest
    container:
      image: dockware/dev:6.5.0.0-rc1
      env:
        PHP_VERSION: 8.1
      volumes:
        - ./src:/var/www/html

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y php8.1-gmp
          cd /var/www/html
          composer require hardcastle/xrpl_php dev-master
          composer require --dev phpunit/phpunit ^9
          cd src/custom/plugins/LedgerDirect
      - name: Run PHPUnit
        run: make phpunit

